var wms_layers = [];


        var lyr_EsriGraydark_0 = new ol.layer.Tile({
            'title': 'Esri Gray (dark)',
            'type': 'base',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
    attributions: ' ',
                url: 'http://services.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Dark_Gray_Base/MapServer/tile/{z}/{y}/{x}'
            })
        });
var format_Mar21_1 = new ol.format.GeoJSON();
var features_Mar21_1 = format_Mar21_1.readFeatures(json_Mar21_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Mar21_1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Mar21_1.addFeatures(features_Mar21_1);
var lyr_Mar21_1 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Mar21_1, 
                style: style_Mar21_1,
                interactive: true,
    title: 'Mar.21<br />\
    <img src="styles/legend/Mar21_1_0.png" /> 269367 - 325187<br />\
    <img src="styles/legend/Mar21_1_1.png" /> 325187 - 386188<br />\
    <img src="styles/legend/Mar21_1_2.png" /> 386188 - 473190<br />\
    <img src="styles/legend/Mar21_1_3.png" /> 473190 - 568169<br />\
    <img src="styles/legend/Mar21_1_4.png" /> 568169 - 774045<br />'
        });
var format_Feb21_2 = new ol.format.GeoJSON();
var features_Feb21_2 = format_Feb21_2.readFeatures(json_Feb21_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Feb21_2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Feb21_2.addFeatures(features_Feb21_2);
var lyr_Feb21_2 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Feb21_2, 
                style: style_Feb21_2,
                interactive: true,
    title: 'Feb.21<br />\
    <img src="styles/legend/Feb21_2_0.png" /> 269367 - 325187<br />\
    <img src="styles/legend/Feb21_2_1.png" /> 325187 - 386188<br />\
    <img src="styles/legend/Feb21_2_2.png" /> 386188 - 473190<br />\
    <img src="styles/legend/Feb21_2_3.png" /> 473190 - 568169<br />\
    <img src="styles/legend/Feb21_2_4.png" /> 568169 - 765894<br />'
        });
var format_Jan21_3 = new ol.format.GeoJSON();
var features_Jan21_3 = format_Jan21_3.readFeatures(json_Jan21_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Jan21_3 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Jan21_3.addFeatures(features_Jan21_3);
var lyr_Jan21_3 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Jan21_3, 
                style: style_Jan21_3,
                interactive: true,
    title: 'Jan.21<br />\
    <img src="styles/legend/Jan21_3_0.png" /> 269367 - 325187<br />\
    <img src="styles/legend/Jan21_3_1.png" /> 325187 - 386188<br />\
    <img src="styles/legend/Jan21_3_2.png" /> 386188 - 473190<br />\
    <img src="styles/legend/Jan21_3_3.png" /> 473190 - 568169<br />\
    <img src="styles/legend/Jan21_3_4.png" /> 568169 - 756907<br />'
        });
var format_Dec20_4 = new ol.format.GeoJSON();
var features_Dec20_4 = format_Dec20_4.readFeatures(json_Dec20_4, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Dec20_4 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Dec20_4.addFeatures(features_Dec20_4);
var lyr_Dec20_4 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Dec20_4, 
                style: style_Dec20_4,
                interactive: true,
    title: 'Dec.20<br />\
    <img src="styles/legend/Dec20_4_0.png" /> 267367 - 325187<br />\
    <img src="styles/legend/Dec20_4_1.png" /> 325187 - 386188<br />\
    <img src="styles/legend/Dec20_4_2.png" /> 386188 - 473190<br />\
    <img src="styles/legend/Dec20_4_3.png" /> 473190 - 568169<br />\
    <img src="styles/legend/Dec20_4_4.png" /> 568169 - 748537<br />'
        });
var format_Mar20_5 = new ol.format.GeoJSON();
var features_Mar20_5 = format_Mar20_5.readFeatures(json_Mar20_5, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Mar20_5 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Mar20_5.addFeatures(features_Mar20_5);
var lyr_Mar20_5 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Mar20_5, 
                style: style_Mar20_5,
                interactive: true,
    title: 'Mar.20<br />\
    <img src="styles/legend/Mar20_5_0.png" /> 269367 - 325187<br />\
    <img src="styles/legend/Mar20_5_1.png" /> 325187 - 386188<br />\
    <img src="styles/legend/Mar20_5_2.png" /> 386188 - 473190<br />\
    <img src="styles/legend/Mar20_5_3.png" /> 473190 - 567169<br />\
    <img src="styles/legend/Mar20_5_4.png" /> 567169 - 674764<br />'
        });
var format_Feb20_6 = new ol.format.GeoJSON();
var features_Feb20_6 = format_Feb20_6.readFeatures(json_Feb20_6, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Feb20_6 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Feb20_6.addFeatures(features_Feb20_6);
var lyr_Feb20_6 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Feb20_6, 
                style: style_Feb20_6,
                interactive: true,
    title: 'Feb.20<br />\
    <img src="styles/legend/Feb20_6_0.png" /> 269367 - 325187<br />\
    <img src="styles/legend/Feb20_6_1.png" /> 325187 - 386188<br />\
    <img src="styles/legend/Feb20_6_2.png" /> 386188 - 473190<br />\
    <img src="styles/legend/Feb20_6_3.png" /> 473190 - 568169<br />\
    <img src="styles/legend/Feb20_6_4.png" /> 568169 - 669115<br />'
        });
var format_Jan20_7 = new ol.format.GeoJSON();
var features_Jan20_7 = format_Jan20_7.readFeatures(json_Jan20_7, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Jan20_7 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Jan20_7.addFeatures(features_Jan20_7);
var lyr_Jan20_7 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Jan20_7, 
                style: style_Jan20_7,
                interactive: true,
    title: 'Jan.20<br />\
    <img src="styles/legend/Jan20_7_0.png" /> 269367 - 325187<br />\
    <img src="styles/legend/Jan20_7_1.png" /> 325187 - 386188<br />\
    <img src="styles/legend/Jan20_7_2.png" /> 386188 - 473190<br />\
    <img src="styles/legend/Jan20_7_3.png" /> 473190 - 568169<br />\
    <img src="styles/legend/Jan20_7_4.png" /> 568169 - 665676<br />'
        });
var format_Dec19_8 = new ol.format.GeoJSON();
var features_Dec19_8 = format_Dec19_8.readFeatures(json_Dec19_8, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Dec19_8 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Dec19_8.addFeatures(features_Dec19_8);
var lyr_Dec19_8 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Dec19_8, 
                style: style_Dec19_8,
                interactive: true,
    title: 'Dec.19<br />\
    <img src="styles/legend/Dec19_8_0.png" /> 269367 - 325187<br />\
    <img src="styles/legend/Dec19_8_1.png" /> 325187 - 386188<br />\
    <img src="styles/legend/Dec19_8_2.png" /> 386188 - 473190<br />\
    <img src="styles/legend/Dec19_8_3.png" /> 473190 - 568169<br />\
    <img src="styles/legend/Dec19_8_4.png" /> 568169 - 661442<br />'
        });

lyr_EsriGraydark_0.setVisible(true);lyr_Mar21_1.setVisible(true);lyr_Feb21_2.setVisible(true);lyr_Jan21_3.setVisible(true);lyr_Dec20_4.setVisible(true);lyr_Mar20_5.setVisible(true);lyr_Feb20_6.setVisible(true);lyr_Jan20_7.setVisible(true);lyr_Dec19_8.setVisible(true);
var layersList = [lyr_EsriGraydark_0,lyr_Mar21_1,lyr_Feb21_2,lyr_Jan21_3,lyr_Dec20_4,lyr_Mar20_5,lyr_Feb20_6,lyr_Jan20_7,lyr_Dec19_8];
lyr_Mar21_1.set('fieldAliases', {'OBJECTID': 'OBJECTID', 'ZIP5': 'ZIP5', 'COUNTYNBR': 'COUNTYNBR', 'NAME': 'NAME', 'SYMBOL': 'SYMBOL', 'SHAPE_Leng': 'SHAPE_Leng', 'SHAPE_Area': 'SHAPE_Area', 'Case Rate': 'Case Rate', 'Population': 'Population', 'White': 'White', 'Black': 'Black', 'Asian': 'Asian', 'Hispanic': 'Hispanic', 'Dec. 19': 'Dec. 19', 'Jan.20': 'Jan.20', 'Feb.20': 'Feb.20', 'Mar.20': 'Mar.20', 'Dec.20': 'Dec.20', 'Jan.21': 'Jan.21', 'Feb.21': 'Feb.21', 'Mar.21': 'Mar.21', 'SLCo_Regio': 'SLCo_Regio', 'SLCo_SizeR': 'SLCo_SizeR', 'SLCo_12/31': 'SLCo_12/31', 'SLCo_1/31/': 'SLCo_1/31/', 'SLCo_2/29/': 'SLCo_2/29/', 'SLCo_3/31/': 'SLCo_3/31/', 'SLCo_4/30/': 'SLCo_4/30/', 'SLCo_5/31/': 'SLCo_5/31/', 'SLCo_6/30/': 'SLCo_6/30/', 'SLCo_7/31/': 'SLCo_7/31/', 'SLCo_8/31/': 'SLCo_8/31/', 'SLCo_9/30/': 'SLCo_9/30/', 'SLCo_10/31': 'SLCo_10/31', 'SLCo_11/30': 'SLCo_11/30', 'SLCo_12/_1': 'SLCo_12/_1', 'SLCo_1/3_1': 'SLCo_1/3_1', 'SLCo_2/28/': 'SLCo_2/28/', 'SLCo_3/3_1': 'SLCo_3/3_1', 'SLCo_ZIP_c': 'SLCo_ZIP_c', 'SLCo_Case_': 'SLCo_Case_', 'SLCo_Morta': 'SLCo_Morta', 'SLCo_Vax_c': 'SLCo_Vax_c', 'Zip.Pop_id': 'Zip.Pop_id', 'Zip.Pop_To': 'Zip.Pop_To', 'Zip.Pop_Wh': 'Zip.Pop_Wh', 'Zip.Pop_%': 'Zip.Pop_%', 'Zip.Pop_Bl': 'Zip.Pop_Bl', 'Zip.Pop__1': 'Zip.Pop__1', 'Zip.Pop_As': 'Zip.Pop_As', 'Zip.Pop__2': 'Zip.Pop__2', 'Zip.Pop_Hi': 'Zip.Pop_Hi', 'Zip.Pop__3': 'Zip.Pop__3', });
lyr_Feb21_2.set('fieldAliases', {'OBJECTID': 'OBJECTID', 'ZIP5': 'ZIP5', 'COUNTYNBR': 'COUNTYNBR', 'NAME': 'NAME', 'SYMBOL': 'SYMBOL', 'SHAPE_Leng': 'SHAPE_Leng', 'SHAPE_Area': 'SHAPE_Area', 'Case Rate': 'Case Rate', 'Population': 'Population', 'White': 'White', 'Black': 'Black', 'Asian': 'Asian', 'Hispanic': 'Hispanic', 'Dec. 19': 'Dec. 19', 'Jan.20': 'Jan.20', 'Feb.20': 'Feb.20', 'Mar.20': 'Mar.20', 'Dec.20': 'Dec.20', 'Jan.21': 'Jan.21', 'Feb.21': 'Feb.21', 'Mar.21': 'Mar.21', 'SLCo_Regio': 'SLCo_Regio', 'SLCo_SizeR': 'SLCo_SizeR', 'SLCo_12/31': 'SLCo_12/31', 'SLCo_1/31/': 'SLCo_1/31/', 'SLCo_2/29/': 'SLCo_2/29/', 'SLCo_3/31/': 'SLCo_3/31/', 'SLCo_4/30/': 'SLCo_4/30/', 'SLCo_5/31/': 'SLCo_5/31/', 'SLCo_6/30/': 'SLCo_6/30/', 'SLCo_7/31/': 'SLCo_7/31/', 'SLCo_8/31/': 'SLCo_8/31/', 'SLCo_9/30/': 'SLCo_9/30/', 'SLCo_10/31': 'SLCo_10/31', 'SLCo_11/30': 'SLCo_11/30', 'SLCo_12/_1': 'SLCo_12/_1', 'SLCo_1/3_1': 'SLCo_1/3_1', 'SLCo_2/28/': 'SLCo_2/28/', 'SLCo_3/3_1': 'SLCo_3/3_1', 'SLCo_ZIP_c': 'SLCo_ZIP_c', 'SLCo_Case_': 'SLCo_Case_', 'SLCo_Morta': 'SLCo_Morta', 'SLCo_Vax_c': 'SLCo_Vax_c', 'Zip.Pop_id': 'Zip.Pop_id', 'Zip.Pop_To': 'Zip.Pop_To', 'Zip.Pop_Wh': 'Zip.Pop_Wh', 'Zip.Pop_%': 'Zip.Pop_%', 'Zip.Pop_Bl': 'Zip.Pop_Bl', 'Zip.Pop__1': 'Zip.Pop__1', 'Zip.Pop_As': 'Zip.Pop_As', 'Zip.Pop__2': 'Zip.Pop__2', 'Zip.Pop_Hi': 'Zip.Pop_Hi', 'Zip.Pop__3': 'Zip.Pop__3', });
lyr_Jan21_3.set('fieldAliases', {'OBJECTID': 'OBJECTID', 'ZIP5': 'ZIP5', 'COUNTYNBR': 'COUNTYNBR', 'NAME': 'NAME', 'SYMBOL': 'SYMBOL', 'SHAPE_Leng': 'SHAPE_Leng', 'SHAPE_Area': 'SHAPE_Area', 'Case Rate': 'Case Rate', 'Population': 'Population', 'White': 'White', 'Black': 'Black', 'Asian': 'Asian', 'Hispanic': 'Hispanic', 'Dec. 19': 'Dec. 19', 'Jan.20': 'Jan.20', 'Feb.20': 'Feb.20', 'Mar.20': 'Mar.20', 'Dec.20': 'Dec.20', 'Jan.21': 'Jan.21', 'Feb.21': 'Feb.21', 'Mar.21': 'Mar.21', 'SLCo_Regio': 'SLCo_Regio', 'SLCo_SizeR': 'SLCo_SizeR', 'SLCo_12/31': 'SLCo_12/31', 'SLCo_1/31/': 'SLCo_1/31/', 'SLCo_2/29/': 'SLCo_2/29/', 'SLCo_3/31/': 'SLCo_3/31/', 'SLCo_4/30/': 'SLCo_4/30/', 'SLCo_5/31/': 'SLCo_5/31/', 'SLCo_6/30/': 'SLCo_6/30/', 'SLCo_7/31/': 'SLCo_7/31/', 'SLCo_8/31/': 'SLCo_8/31/', 'SLCo_9/30/': 'SLCo_9/30/', 'SLCo_10/31': 'SLCo_10/31', 'SLCo_11/30': 'SLCo_11/30', 'SLCo_12/_1': 'SLCo_12/_1', 'SLCo_1/3_1': 'SLCo_1/3_1', 'SLCo_2/28/': 'SLCo_2/28/', 'SLCo_3/3_1': 'SLCo_3/3_1', 'SLCo_ZIP_c': 'SLCo_ZIP_c', 'SLCo_Case_': 'SLCo_Case_', 'SLCo_Morta': 'SLCo_Morta', 'SLCo_Vax_c': 'SLCo_Vax_c', 'Zip.Pop_id': 'Zip.Pop_id', 'Zip.Pop_To': 'Zip.Pop_To', 'Zip.Pop_Wh': 'Zip.Pop_Wh', 'Zip.Pop_%': 'Zip.Pop_%', 'Zip.Pop_Bl': 'Zip.Pop_Bl', 'Zip.Pop__1': 'Zip.Pop__1', 'Zip.Pop_As': 'Zip.Pop_As', 'Zip.Pop__2': 'Zip.Pop__2', 'Zip.Pop_Hi': 'Zip.Pop_Hi', 'Zip.Pop__3': 'Zip.Pop__3', });
lyr_Dec20_4.set('fieldAliases', {'OBJECTID': 'OBJECTID', 'ZIP5': 'ZIP5', 'COUNTYNBR': 'COUNTYNBR', 'NAME': 'NAME', 'SYMBOL': 'SYMBOL', 'SHAPE_Leng': 'SHAPE_Leng', 'SHAPE_Area': 'SHAPE_Area', 'Case Rate': 'Case Rate', 'Population': 'Population', 'White': 'White', 'Black': 'Black', 'Asian': 'Asian', 'Hispanic': 'Hispanic', 'Dec. 19': 'Dec. 19', 'Jan.20': 'Jan.20', 'Feb.20': 'Feb.20', 'Mar.20': 'Mar.20', 'Dec.20': 'Dec.20', 'Jan.21': 'Jan.21', 'Feb.21': 'Feb.21', 'Mar.21': 'Mar.21', 'SLCo_Regio': 'SLCo_Regio', 'SLCo_SizeR': 'SLCo_SizeR', 'SLCo_12/31': 'SLCo_12/31', 'SLCo_1/31/': 'SLCo_1/31/', 'SLCo_2/29/': 'SLCo_2/29/', 'SLCo_3/31/': 'SLCo_3/31/', 'SLCo_4/30/': 'SLCo_4/30/', 'SLCo_5/31/': 'SLCo_5/31/', 'SLCo_6/30/': 'SLCo_6/30/', 'SLCo_7/31/': 'SLCo_7/31/', 'SLCo_8/31/': 'SLCo_8/31/', 'SLCo_9/30/': 'SLCo_9/30/', 'SLCo_10/31': 'SLCo_10/31', 'SLCo_11/30': 'SLCo_11/30', 'SLCo_12/_1': 'SLCo_12/_1', 'SLCo_1/3_1': 'SLCo_1/3_1', 'SLCo_2/28/': 'SLCo_2/28/', 'SLCo_3/3_1': 'SLCo_3/3_1', 'SLCo_ZIP_c': 'SLCo_ZIP_c', 'SLCo_Case_': 'SLCo_Case_', 'SLCo_Morta': 'SLCo_Morta', 'SLCo_Vax_c': 'SLCo_Vax_c', 'Zip.Pop_id': 'Zip.Pop_id', 'Zip.Pop_To': 'Zip.Pop_To', 'Zip.Pop_Wh': 'Zip.Pop_Wh', 'Zip.Pop_%': 'Zip.Pop_%', 'Zip.Pop_Bl': 'Zip.Pop_Bl', 'Zip.Pop__1': 'Zip.Pop__1', 'Zip.Pop_As': 'Zip.Pop_As', 'Zip.Pop__2': 'Zip.Pop__2', 'Zip.Pop_Hi': 'Zip.Pop_Hi', 'Zip.Pop__3': 'Zip.Pop__3', });
lyr_Mar20_5.set('fieldAliases', {'OBJECTID': 'OBJECTID', 'ZIP5': 'ZIP5', 'COUNTYNBR': 'COUNTYNBR', 'NAME': 'NAME', 'SYMBOL': 'SYMBOL', 'SHAPE_Leng': 'SHAPE_Leng', 'SHAPE_Area': 'SHAPE_Area', 'Case Rate': 'Case Rate', 'Population': 'Population', 'White': 'White', 'Black': 'Black', 'Asian': 'Asian', 'Hispanic': 'Hispanic', 'Dec. 19': 'Dec. 19', 'Jan.20': 'Jan.20', 'Feb.20': 'Feb.20', 'Mar.20': 'Mar.20', 'Dec.20': 'Dec.20', 'Jan.21': 'Jan.21', 'Feb.21': 'Feb.21', 'Mar.21': 'Mar.21', 'SLCo_Regio': 'SLCo_Regio', 'SLCo_SizeR': 'SLCo_SizeR', 'SLCo_12/31': 'SLCo_12/31', 'SLCo_1/31/': 'SLCo_1/31/', 'SLCo_2/29/': 'SLCo_2/29/', 'SLCo_3/31/': 'SLCo_3/31/', 'SLCo_4/30/': 'SLCo_4/30/', 'SLCo_5/31/': 'SLCo_5/31/', 'SLCo_6/30/': 'SLCo_6/30/', 'SLCo_7/31/': 'SLCo_7/31/', 'SLCo_8/31/': 'SLCo_8/31/', 'SLCo_9/30/': 'SLCo_9/30/', 'SLCo_10/31': 'SLCo_10/31', 'SLCo_11/30': 'SLCo_11/30', 'SLCo_12/_1': 'SLCo_12/_1', 'SLCo_1/3_1': 'SLCo_1/3_1', 'SLCo_2/28/': 'SLCo_2/28/', 'SLCo_3/3_1': 'SLCo_3/3_1', 'SLCo_ZIP_c': 'SLCo_ZIP_c', 'SLCo_Case_': 'SLCo_Case_', 'SLCo_Morta': 'SLCo_Morta', 'SLCo_Vax_c': 'SLCo_Vax_c', 'Zip.Pop_id': 'Zip.Pop_id', 'Zip.Pop_To': 'Zip.Pop_To', 'Zip.Pop_Wh': 'Zip.Pop_Wh', 'Zip.Pop_%': 'Zip.Pop_%', 'Zip.Pop_Bl': 'Zip.Pop_Bl', 'Zip.Pop__1': 'Zip.Pop__1', 'Zip.Pop_As': 'Zip.Pop_As', 'Zip.Pop__2': 'Zip.Pop__2', 'Zip.Pop_Hi': 'Zip.Pop_Hi', 'Zip.Pop__3': 'Zip.Pop__3', });
lyr_Feb20_6.set('fieldAliases', {'OBJECTID': 'OBJECTID', 'ZIP5': 'ZIP5', 'COUNTYNBR': 'COUNTYNBR', 'NAME': 'NAME', 'SYMBOL': 'SYMBOL', 'SHAPE_Leng': 'SHAPE_Leng', 'SHAPE_Area': 'SHAPE_Area', 'Case Rate': 'Case Rate', 'Population': 'Population', 'White': 'White', 'Black': 'Black', 'Asian': 'Asian', 'Hispanic': 'Hispanic', 'Dec. 19': 'Dec. 19', 'Jan.20': 'Jan.20', 'Feb.20': 'Feb.20', 'Mar.20': 'Mar.20', 'Dec.20': 'Dec.20', 'Jan.21': 'Jan.21', 'Feb.21': 'Feb.21', 'Mar.21': 'Mar.21', 'SLCo_Regio': 'SLCo_Regio', 'SLCo_SizeR': 'SLCo_SizeR', 'SLCo_12/31': 'SLCo_12/31', 'SLCo_1/31/': 'SLCo_1/31/', 'SLCo_2/29/': 'SLCo_2/29/', 'SLCo_3/31/': 'SLCo_3/31/', 'SLCo_4/30/': 'SLCo_4/30/', 'SLCo_5/31/': 'SLCo_5/31/', 'SLCo_6/30/': 'SLCo_6/30/', 'SLCo_7/31/': 'SLCo_7/31/', 'SLCo_8/31/': 'SLCo_8/31/', 'SLCo_9/30/': 'SLCo_9/30/', 'SLCo_10/31': 'SLCo_10/31', 'SLCo_11/30': 'SLCo_11/30', 'SLCo_12/_1': 'SLCo_12/_1', 'SLCo_1/3_1': 'SLCo_1/3_1', 'SLCo_2/28/': 'SLCo_2/28/', 'SLCo_3/3_1': 'SLCo_3/3_1', 'SLCo_ZIP_c': 'SLCo_ZIP_c', 'SLCo_Case_': 'SLCo_Case_', 'SLCo_Morta': 'SLCo_Morta', 'SLCo_Vax_c': 'SLCo_Vax_c', 'Zip.Pop_id': 'Zip.Pop_id', 'Zip.Pop_To': 'Zip.Pop_To', 'Zip.Pop_Wh': 'Zip.Pop_Wh', 'Zip.Pop_%': 'Zip.Pop_%', 'Zip.Pop_Bl': 'Zip.Pop_Bl', 'Zip.Pop__1': 'Zip.Pop__1', 'Zip.Pop_As': 'Zip.Pop_As', 'Zip.Pop__2': 'Zip.Pop__2', 'Zip.Pop_Hi': 'Zip.Pop_Hi', 'Zip.Pop__3': 'Zip.Pop__3', });
lyr_Jan20_7.set('fieldAliases', {'OBJECTID': 'OBJECTID', 'ZIP5': 'ZIP5', 'COUNTYNBR': 'COUNTYNBR', 'NAME': 'NAME', 'SYMBOL': 'SYMBOL', 'SHAPE_Leng': 'SHAPE_Leng', 'SHAPE_Area': 'SHAPE_Area', 'Case Rate': 'Case Rate', 'Population': 'Population', 'White': 'White', 'Black': 'Black', 'Asian': 'Asian', 'Hispanic': 'Hispanic', 'Dec. 19': 'Dec. 19', 'Jan.20': 'Jan.20', 'Feb.20': 'Feb.20', 'Mar.20': 'Mar.20', 'Dec.20': 'Dec.20', 'Jan.21': 'Jan.21', 'Feb.21': 'Feb.21', 'Mar.21': 'Mar.21', 'SLCo_Regio': 'SLCo_Regio', 'SLCo_SizeR': 'SLCo_SizeR', 'SLCo_12/31': 'SLCo_12/31', 'SLCo_1/31/': 'SLCo_1/31/', 'SLCo_2/29/': 'SLCo_2/29/', 'SLCo_3/31/': 'SLCo_3/31/', 'SLCo_4/30/': 'SLCo_4/30/', 'SLCo_5/31/': 'SLCo_5/31/', 'SLCo_6/30/': 'SLCo_6/30/', 'SLCo_7/31/': 'SLCo_7/31/', 'SLCo_8/31/': 'SLCo_8/31/', 'SLCo_9/30/': 'SLCo_9/30/', 'SLCo_10/31': 'SLCo_10/31', 'SLCo_11/30': 'SLCo_11/30', 'SLCo_12/_1': 'SLCo_12/_1', 'SLCo_1/3_1': 'SLCo_1/3_1', 'SLCo_2/28/': 'SLCo_2/28/', 'SLCo_3/3_1': 'SLCo_3/3_1', 'SLCo_ZIP_c': 'SLCo_ZIP_c', 'SLCo_Case_': 'SLCo_Case_', 'SLCo_Morta': 'SLCo_Morta', 'SLCo_Vax_c': 'SLCo_Vax_c', 'Zip.Pop_id': 'Zip.Pop_id', 'Zip.Pop_To': 'Zip.Pop_To', 'Zip.Pop_Wh': 'Zip.Pop_Wh', 'Zip.Pop_%': 'Zip.Pop_%', 'Zip.Pop_Bl': 'Zip.Pop_Bl', 'Zip.Pop__1': 'Zip.Pop__1', 'Zip.Pop_As': 'Zip.Pop_As', 'Zip.Pop__2': 'Zip.Pop__2', 'Zip.Pop_Hi': 'Zip.Pop_Hi', 'Zip.Pop__3': 'Zip.Pop__3', });
lyr_Dec19_8.set('fieldAliases', {'OBJECTID': 'OBJECTID', 'ZIP5': 'ZIP5', 'COUNTYNBR': 'COUNTYNBR', 'NAME': 'NAME', 'SYMBOL': 'SYMBOL', 'SHAPE_Leng': 'SHAPE_Leng', 'SHAPE_Area': 'SHAPE_Area', 'Case Rate': 'Case Rate', 'Population': 'Population', 'White': 'White', 'Black': 'Black', 'Asian': 'Asian', 'Hispanic': 'Hispanic', 'Dec. 19': 'Dec. 19', 'Jan.20': 'Jan.20', 'Feb.20': 'Feb.20', 'Mar.20': 'Mar.20', 'Dec.20': 'Dec.20', 'Jan.21': 'Jan.21', 'Feb.21': 'Feb.21', 'Mar.21': 'Mar.21', 'SLCo_Regio': 'SLCo_Regio', 'SLCo_SizeR': 'SLCo_SizeR', 'SLCo_12/31': 'SLCo_12/31', 'SLCo_1/31/': 'SLCo_1/31/', 'SLCo_2/29/': 'SLCo_2/29/', 'SLCo_3/31/': 'SLCo_3/31/', 'SLCo_4/30/': 'SLCo_4/30/', 'SLCo_5/31/': 'SLCo_5/31/', 'SLCo_6/30/': 'SLCo_6/30/', 'SLCo_7/31/': 'SLCo_7/31/', 'SLCo_8/31/': 'SLCo_8/31/', 'SLCo_9/30/': 'SLCo_9/30/', 'SLCo_10/31': 'SLCo_10/31', 'SLCo_11/30': 'SLCo_11/30', 'SLCo_12/_1': 'SLCo_12/_1', 'SLCo_1/3_1': 'SLCo_1/3_1', 'SLCo_2/28/': 'SLCo_2/28/', 'SLCo_3/3_1': 'SLCo_3/3_1', 'SLCo_ZIP_c': 'SLCo_ZIP_c', 'SLCo_Case_': 'SLCo_Case_', 'SLCo_Morta': 'SLCo_Morta', 'SLCo_Vax_c': 'SLCo_Vax_c', 'Zip.Pop_id': 'Zip.Pop_id', 'Zip.Pop_To': 'Zip.Pop_To', 'Zip.Pop_Wh': 'Zip.Pop_Wh', 'Zip.Pop_%': 'Zip.Pop_%', 'Zip.Pop_Bl': 'Zip.Pop_Bl', 'Zip.Pop__1': 'Zip.Pop__1', 'Zip.Pop_As': 'Zip.Pop_As', 'Zip.Pop__2': 'Zip.Pop__2', 'Zip.Pop_Hi': 'Zip.Pop_Hi', 'Zip.Pop__3': 'Zip.Pop__3', });
lyr_Mar21_1.set('fieldImages', {'OBJECTID': 'TextEdit', 'ZIP5': 'TextEdit', 'COUNTYNBR': 'TextEdit', 'NAME': 'TextEdit', 'SYMBOL': 'TextEdit', 'SHAPE_Leng': 'TextEdit', 'SHAPE_Area': 'TextEdit', 'Case Rate': 'TextEdit', 'Population': 'TextEdit', 'White': 'TextEdit', 'Black': 'TextEdit', 'Asian': 'TextEdit', 'Hispanic': 'TextEdit', 'Dec. 19': 'TextEdit', 'Jan.20': 'TextEdit', 'Feb.20': 'TextEdit', 'Mar.20': 'TextEdit', 'Dec.20': 'TextEdit', 'Jan.21': 'TextEdit', 'Feb.21': 'TextEdit', 'Mar.21': 'TextEdit', 'SLCo_Regio': 'TextEdit', 'SLCo_SizeR': 'TextEdit', 'SLCo_12/31': 'TextEdit', 'SLCo_1/31/': 'TextEdit', 'SLCo_2/29/': 'TextEdit', 'SLCo_3/31/': 'TextEdit', 'SLCo_4/30/': 'TextEdit', 'SLCo_5/31/': 'TextEdit', 'SLCo_6/30/': 'TextEdit', 'SLCo_7/31/': 'TextEdit', 'SLCo_8/31/': 'TextEdit', 'SLCo_9/30/': 'TextEdit', 'SLCo_10/31': 'TextEdit', 'SLCo_11/30': 'TextEdit', 'SLCo_12/_1': 'TextEdit', 'SLCo_1/3_1': 'TextEdit', 'SLCo_2/28/': 'TextEdit', 'SLCo_3/3_1': 'TextEdit', 'SLCo_ZIP_c': 'TextEdit', 'SLCo_Case_': 'TextEdit', 'SLCo_Morta': 'TextEdit', 'SLCo_Vax_c': 'TextEdit', 'Zip.Pop_id': 'TextEdit', 'Zip.Pop_To': 'TextEdit', 'Zip.Pop_Wh': 'TextEdit', 'Zip.Pop_%': 'TextEdit', 'Zip.Pop_Bl': 'TextEdit', 'Zip.Pop__1': 'TextEdit', 'Zip.Pop_As': 'TextEdit', 'Zip.Pop__2': 'TextEdit', 'Zip.Pop_Hi': 'TextEdit', 'Zip.Pop__3': 'TextEdit', });
lyr_Feb21_2.set('fieldImages', {'OBJECTID': 'TextEdit', 'ZIP5': 'TextEdit', 'COUNTYNBR': 'TextEdit', 'NAME': 'TextEdit', 'SYMBOL': 'TextEdit', 'SHAPE_Leng': 'TextEdit', 'SHAPE_Area': 'TextEdit', 'Case Rate': 'TextEdit', 'Population': 'TextEdit', 'White': 'TextEdit', 'Black': 'TextEdit', 'Asian': 'TextEdit', 'Hispanic': 'TextEdit', 'Dec. 19': 'TextEdit', 'Jan.20': 'TextEdit', 'Feb.20': 'TextEdit', 'Mar.20': 'TextEdit', 'Dec.20': 'TextEdit', 'Jan.21': 'TextEdit', 'Feb.21': 'TextEdit', 'Mar.21': 'TextEdit', 'SLCo_Regio': 'TextEdit', 'SLCo_SizeR': 'TextEdit', 'SLCo_12/31': 'TextEdit', 'SLCo_1/31/': 'TextEdit', 'SLCo_2/29/': 'TextEdit', 'SLCo_3/31/': 'TextEdit', 'SLCo_4/30/': 'TextEdit', 'SLCo_5/31/': 'TextEdit', 'SLCo_6/30/': 'TextEdit', 'SLCo_7/31/': 'TextEdit', 'SLCo_8/31/': 'TextEdit', 'SLCo_9/30/': 'TextEdit', 'SLCo_10/31': 'TextEdit', 'SLCo_11/30': 'TextEdit', 'SLCo_12/_1': 'TextEdit', 'SLCo_1/3_1': 'TextEdit', 'SLCo_2/28/': 'TextEdit', 'SLCo_3/3_1': 'TextEdit', 'SLCo_ZIP_c': 'TextEdit', 'SLCo_Case_': 'TextEdit', 'SLCo_Morta': 'TextEdit', 'SLCo_Vax_c': 'TextEdit', 'Zip.Pop_id': 'TextEdit', 'Zip.Pop_To': 'TextEdit', 'Zip.Pop_Wh': 'TextEdit', 'Zip.Pop_%': 'TextEdit', 'Zip.Pop_Bl': 'TextEdit', 'Zip.Pop__1': 'TextEdit', 'Zip.Pop_As': 'TextEdit', 'Zip.Pop__2': 'TextEdit', 'Zip.Pop_Hi': 'TextEdit', 'Zip.Pop__3': 'TextEdit', });
lyr_Jan21_3.set('fieldImages', {'OBJECTID': 'TextEdit', 'ZIP5': 'TextEdit', 'COUNTYNBR': 'TextEdit', 'NAME': 'TextEdit', 'SYMBOL': 'TextEdit', 'SHAPE_Leng': 'TextEdit', 'SHAPE_Area': 'TextEdit', 'Case Rate': 'TextEdit', 'Population': 'TextEdit', 'White': 'TextEdit', 'Black': 'TextEdit', 'Asian': 'TextEdit', 'Hispanic': 'TextEdit', 'Dec. 19': 'TextEdit', 'Jan.20': 'TextEdit', 'Feb.20': 'TextEdit', 'Mar.20': 'TextEdit', 'Dec.20': 'TextEdit', 'Jan.21': 'TextEdit', 'Feb.21': 'TextEdit', 'Mar.21': 'TextEdit', 'SLCo_Regio': 'TextEdit', 'SLCo_SizeR': 'TextEdit', 'SLCo_12/31': 'TextEdit', 'SLCo_1/31/': 'TextEdit', 'SLCo_2/29/': 'TextEdit', 'SLCo_3/31/': 'TextEdit', 'SLCo_4/30/': 'TextEdit', 'SLCo_5/31/': 'TextEdit', 'SLCo_6/30/': 'TextEdit', 'SLCo_7/31/': 'TextEdit', 'SLCo_8/31/': 'TextEdit', 'SLCo_9/30/': 'TextEdit', 'SLCo_10/31': 'TextEdit', 'SLCo_11/30': 'TextEdit', 'SLCo_12/_1': 'TextEdit', 'SLCo_1/3_1': 'TextEdit', 'SLCo_2/28/': 'TextEdit', 'SLCo_3/3_1': 'TextEdit', 'SLCo_ZIP_c': 'TextEdit', 'SLCo_Case_': 'TextEdit', 'SLCo_Morta': 'TextEdit', 'SLCo_Vax_c': 'TextEdit', 'Zip.Pop_id': 'TextEdit', 'Zip.Pop_To': 'TextEdit', 'Zip.Pop_Wh': 'TextEdit', 'Zip.Pop_%': 'TextEdit', 'Zip.Pop_Bl': 'TextEdit', 'Zip.Pop__1': 'TextEdit', 'Zip.Pop_As': 'TextEdit', 'Zip.Pop__2': 'TextEdit', 'Zip.Pop_Hi': 'TextEdit', 'Zip.Pop__3': 'TextEdit', });
lyr_Dec20_4.set('fieldImages', {'OBJECTID': 'TextEdit', 'ZIP5': 'TextEdit', 'COUNTYNBR': 'TextEdit', 'NAME': 'TextEdit', 'SYMBOL': 'TextEdit', 'SHAPE_Leng': 'TextEdit', 'SHAPE_Area': 'TextEdit', 'Case Rate': 'TextEdit', 'Population': 'TextEdit', 'White': 'TextEdit', 'Black': 'TextEdit', 'Asian': 'TextEdit', 'Hispanic': 'TextEdit', 'Dec. 19': 'TextEdit', 'Jan.20': 'TextEdit', 'Feb.20': 'TextEdit', 'Mar.20': 'TextEdit', 'Dec.20': 'TextEdit', 'Jan.21': 'TextEdit', 'Feb.21': 'TextEdit', 'Mar.21': 'TextEdit', 'SLCo_Regio': 'TextEdit', 'SLCo_SizeR': 'TextEdit', 'SLCo_12/31': 'TextEdit', 'SLCo_1/31/': 'TextEdit', 'SLCo_2/29/': 'TextEdit', 'SLCo_3/31/': 'TextEdit', 'SLCo_4/30/': 'TextEdit', 'SLCo_5/31/': 'TextEdit', 'SLCo_6/30/': 'TextEdit', 'SLCo_7/31/': 'TextEdit', 'SLCo_8/31/': 'TextEdit', 'SLCo_9/30/': 'TextEdit', 'SLCo_10/31': 'TextEdit', 'SLCo_11/30': 'TextEdit', 'SLCo_12/_1': 'TextEdit', 'SLCo_1/3_1': 'TextEdit', 'SLCo_2/28/': 'TextEdit', 'SLCo_3/3_1': 'TextEdit', 'SLCo_ZIP_c': 'TextEdit', 'SLCo_Case_': 'TextEdit', 'SLCo_Morta': 'TextEdit', 'SLCo_Vax_c': 'TextEdit', 'Zip.Pop_id': 'TextEdit', 'Zip.Pop_To': 'TextEdit', 'Zip.Pop_Wh': 'TextEdit', 'Zip.Pop_%': 'TextEdit', 'Zip.Pop_Bl': 'TextEdit', 'Zip.Pop__1': 'TextEdit', 'Zip.Pop_As': 'TextEdit', 'Zip.Pop__2': 'TextEdit', 'Zip.Pop_Hi': 'TextEdit', 'Zip.Pop__3': 'TextEdit', });
lyr_Mar20_5.set('fieldImages', {'OBJECTID': 'TextEdit', 'ZIP5': 'TextEdit', 'COUNTYNBR': 'TextEdit', 'NAME': 'TextEdit', 'SYMBOL': 'TextEdit', 'SHAPE_Leng': 'TextEdit', 'SHAPE_Area': 'TextEdit', 'Case Rate': 'TextEdit', 'Population': 'TextEdit', 'White': 'TextEdit', 'Black': 'TextEdit', 'Asian': 'TextEdit', 'Hispanic': 'TextEdit', 'Dec. 19': 'TextEdit', 'Jan.20': 'TextEdit', 'Feb.20': 'TextEdit', 'Mar.20': 'TextEdit', 'Dec.20': 'TextEdit', 'Jan.21': 'TextEdit', 'Feb.21': 'TextEdit', 'Mar.21': 'TextEdit', 'SLCo_Regio': 'TextEdit', 'SLCo_SizeR': 'TextEdit', 'SLCo_12/31': 'TextEdit', 'SLCo_1/31/': 'TextEdit', 'SLCo_2/29/': 'TextEdit', 'SLCo_3/31/': 'TextEdit', 'SLCo_4/30/': 'TextEdit', 'SLCo_5/31/': 'TextEdit', 'SLCo_6/30/': 'TextEdit', 'SLCo_7/31/': 'TextEdit', 'SLCo_8/31/': 'TextEdit', 'SLCo_9/30/': 'TextEdit', 'SLCo_10/31': 'TextEdit', 'SLCo_11/30': 'TextEdit', 'SLCo_12/_1': 'TextEdit', 'SLCo_1/3_1': 'TextEdit', 'SLCo_2/28/': 'TextEdit', 'SLCo_3/3_1': 'TextEdit', 'SLCo_ZIP_c': 'TextEdit', 'SLCo_Case_': 'TextEdit', 'SLCo_Morta': 'TextEdit', 'SLCo_Vax_c': 'TextEdit', 'Zip.Pop_id': 'TextEdit', 'Zip.Pop_To': 'TextEdit', 'Zip.Pop_Wh': 'TextEdit', 'Zip.Pop_%': 'TextEdit', 'Zip.Pop_Bl': 'TextEdit', 'Zip.Pop__1': 'TextEdit', 'Zip.Pop_As': 'TextEdit', 'Zip.Pop__2': 'TextEdit', 'Zip.Pop_Hi': 'TextEdit', 'Zip.Pop__3': 'TextEdit', });
lyr_Feb20_6.set('fieldImages', {'OBJECTID': 'TextEdit', 'ZIP5': 'TextEdit', 'COUNTYNBR': 'TextEdit', 'NAME': 'TextEdit', 'SYMBOL': 'TextEdit', 'SHAPE_Leng': 'TextEdit', 'SHAPE_Area': 'TextEdit', 'Case Rate': 'TextEdit', 'Population': 'TextEdit', 'White': 'TextEdit', 'Black': 'TextEdit', 'Asian': 'TextEdit', 'Hispanic': 'TextEdit', 'Dec. 19': 'TextEdit', 'Jan.20': 'TextEdit', 'Feb.20': 'TextEdit', 'Mar.20': 'TextEdit', 'Dec.20': 'TextEdit', 'Jan.21': 'TextEdit', 'Feb.21': 'TextEdit', 'Mar.21': 'TextEdit', 'SLCo_Regio': 'TextEdit', 'SLCo_SizeR': 'TextEdit', 'SLCo_12/31': 'TextEdit', 'SLCo_1/31/': 'TextEdit', 'SLCo_2/29/': 'TextEdit', 'SLCo_3/31/': 'TextEdit', 'SLCo_4/30/': 'TextEdit', 'SLCo_5/31/': 'TextEdit', 'SLCo_6/30/': 'TextEdit', 'SLCo_7/31/': 'TextEdit', 'SLCo_8/31/': 'TextEdit', 'SLCo_9/30/': 'TextEdit', 'SLCo_10/31': 'TextEdit', 'SLCo_11/30': 'TextEdit', 'SLCo_12/_1': 'TextEdit', 'SLCo_1/3_1': 'TextEdit', 'SLCo_2/28/': 'TextEdit', 'SLCo_3/3_1': 'TextEdit', 'SLCo_ZIP_c': 'TextEdit', 'SLCo_Case_': 'TextEdit', 'SLCo_Morta': 'TextEdit', 'SLCo_Vax_c': 'TextEdit', 'Zip.Pop_id': 'TextEdit', 'Zip.Pop_To': 'TextEdit', 'Zip.Pop_Wh': 'TextEdit', 'Zip.Pop_%': 'TextEdit', 'Zip.Pop_Bl': 'TextEdit', 'Zip.Pop__1': 'TextEdit', 'Zip.Pop_As': 'TextEdit', 'Zip.Pop__2': 'TextEdit', 'Zip.Pop_Hi': 'TextEdit', 'Zip.Pop__3': 'TextEdit', });
lyr_Jan20_7.set('fieldImages', {'OBJECTID': 'TextEdit', 'ZIP5': 'TextEdit', 'COUNTYNBR': 'TextEdit', 'NAME': 'TextEdit', 'SYMBOL': 'TextEdit', 'SHAPE_Leng': 'TextEdit', 'SHAPE_Area': 'TextEdit', 'Case Rate': 'TextEdit', 'Population': 'TextEdit', 'White': 'TextEdit', 'Black': 'TextEdit', 'Asian': 'TextEdit', 'Hispanic': 'TextEdit', 'Dec. 19': 'TextEdit', 'Jan.20': 'TextEdit', 'Feb.20': 'TextEdit', 'Mar.20': 'TextEdit', 'Dec.20': 'TextEdit', 'Jan.21': 'TextEdit', 'Feb.21': 'TextEdit', 'Mar.21': 'TextEdit', 'SLCo_Regio': 'TextEdit', 'SLCo_SizeR': 'TextEdit', 'SLCo_12/31': 'TextEdit', 'SLCo_1/31/': 'TextEdit', 'SLCo_2/29/': 'TextEdit', 'SLCo_3/31/': 'TextEdit', 'SLCo_4/30/': 'TextEdit', 'SLCo_5/31/': 'TextEdit', 'SLCo_6/30/': 'TextEdit', 'SLCo_7/31/': 'TextEdit', 'SLCo_8/31/': 'TextEdit', 'SLCo_9/30/': 'TextEdit', 'SLCo_10/31': 'TextEdit', 'SLCo_11/30': 'TextEdit', 'SLCo_12/_1': 'TextEdit', 'SLCo_1/3_1': 'TextEdit', 'SLCo_2/28/': 'TextEdit', 'SLCo_3/3_1': 'TextEdit', 'SLCo_ZIP_c': 'TextEdit', 'SLCo_Case_': 'TextEdit', 'SLCo_Morta': 'TextEdit', 'SLCo_Vax_c': 'TextEdit', 'Zip.Pop_id': 'TextEdit', 'Zip.Pop_To': 'TextEdit', 'Zip.Pop_Wh': 'TextEdit', 'Zip.Pop_%': 'TextEdit', 'Zip.Pop_Bl': 'TextEdit', 'Zip.Pop__1': 'TextEdit', 'Zip.Pop_As': 'TextEdit', 'Zip.Pop__2': 'TextEdit', 'Zip.Pop_Hi': 'TextEdit', 'Zip.Pop__3': 'TextEdit', });
lyr_Dec19_8.set('fieldImages', {'OBJECTID': 'TextEdit', 'ZIP5': 'TextEdit', 'COUNTYNBR': 'TextEdit', 'NAME': 'TextEdit', 'SYMBOL': 'TextEdit', 'SHAPE_Leng': 'TextEdit', 'SHAPE_Area': 'TextEdit', 'Case Rate': 'TextEdit', 'Population': 'TextEdit', 'White': 'TextEdit', 'Black': 'TextEdit', 'Asian': 'TextEdit', 'Hispanic': 'TextEdit', 'Dec. 19': 'TextEdit', 'Jan.20': 'TextEdit', 'Feb.20': 'TextEdit', 'Mar.20': 'TextEdit', 'Dec.20': 'TextEdit', 'Jan.21': 'TextEdit', 'Feb.21': 'TextEdit', 'Mar.21': 'TextEdit', 'SLCo_Regio': 'TextEdit', 'SLCo_SizeR': 'TextEdit', 'SLCo_12/31': 'TextEdit', 'SLCo_1/31/': 'TextEdit', 'SLCo_2/29/': 'TextEdit', 'SLCo_3/31/': 'TextEdit', 'SLCo_4/30/': 'TextEdit', 'SLCo_5/31/': 'TextEdit', 'SLCo_6/30/': 'TextEdit', 'SLCo_7/31/': 'TextEdit', 'SLCo_8/31/': 'TextEdit', 'SLCo_9/30/': 'TextEdit', 'SLCo_10/31': 'TextEdit', 'SLCo_11/30': 'TextEdit', 'SLCo_12/_1': 'TextEdit', 'SLCo_1/3_1': 'TextEdit', 'SLCo_2/28/': 'TextEdit', 'SLCo_3/3_1': 'TextEdit', 'SLCo_ZIP_c': 'TextEdit', 'SLCo_Case_': 'TextEdit', 'SLCo_Morta': 'TextEdit', 'SLCo_Vax_c': 'TextEdit', 'Zip.Pop_id': 'TextEdit', 'Zip.Pop_To': 'TextEdit', 'Zip.Pop_Wh': 'TextEdit', 'Zip.Pop_%': 'TextEdit', 'Zip.Pop_Bl': 'TextEdit', 'Zip.Pop__1': 'TextEdit', 'Zip.Pop_As': 'TextEdit', 'Zip.Pop__2': 'TextEdit', 'Zip.Pop_Hi': 'TextEdit', 'Zip.Pop__3': 'TextEdit', });
lyr_Mar21_1.set('fieldLabels', {'OBJECTID': 'no label', 'ZIP5': 'no label', 'COUNTYNBR': 'no label', 'NAME': 'no label', 'SYMBOL': 'no label', 'SHAPE_Leng': 'no label', 'SHAPE_Area': 'no label', 'Case Rate': 'no label', 'Population': 'no label', 'White': 'no label', 'Black': 'no label', 'Asian': 'no label', 'Hispanic': 'no label', 'Dec. 19': 'no label', 'Jan.20': 'no label', 'Feb.20': 'no label', 'Mar.20': 'no label', 'Dec.20': 'no label', 'Jan.21': 'no label', 'Feb.21': 'no label', 'Mar.21': 'no label', 'SLCo_Regio': 'no label', 'SLCo_SizeR': 'no label', 'SLCo_12/31': 'no label', 'SLCo_1/31/': 'no label', 'SLCo_2/29/': 'no label', 'SLCo_3/31/': 'no label', 'SLCo_4/30/': 'no label', 'SLCo_5/31/': 'no label', 'SLCo_6/30/': 'no label', 'SLCo_7/31/': 'no label', 'SLCo_8/31/': 'no label', 'SLCo_9/30/': 'no label', 'SLCo_10/31': 'no label', 'SLCo_11/30': 'no label', 'SLCo_12/_1': 'no label', 'SLCo_1/3_1': 'no label', 'SLCo_2/28/': 'no label', 'SLCo_3/3_1': 'no label', 'SLCo_ZIP_c': 'no label', 'SLCo_Case_': 'no label', 'SLCo_Morta': 'no label', 'SLCo_Vax_c': 'no label', 'Zip.Pop_id': 'no label', 'Zip.Pop_To': 'no label', 'Zip.Pop_Wh': 'no label', 'Zip.Pop_%': 'no label', 'Zip.Pop_Bl': 'no label', 'Zip.Pop__1': 'no label', 'Zip.Pop_As': 'no label', 'Zip.Pop__2': 'no label', 'Zip.Pop_Hi': 'no label', 'Zip.Pop__3': 'no label', });
lyr_Feb21_2.set('fieldLabels', {'OBJECTID': 'no label', 'ZIP5': 'no label', 'COUNTYNBR': 'no label', 'NAME': 'no label', 'SYMBOL': 'no label', 'SHAPE_Leng': 'no label', 'SHAPE_Area': 'no label', 'Case Rate': 'no label', 'Population': 'no label', 'White': 'no label', 'Black': 'no label', 'Asian': 'no label', 'Hispanic': 'no label', 'Dec. 19': 'no label', 'Jan.20': 'no label', 'Feb.20': 'no label', 'Mar.20': 'no label', 'Dec.20': 'no label', 'Jan.21': 'no label', 'Feb.21': 'no label', 'Mar.21': 'no label', 'SLCo_Regio': 'no label', 'SLCo_SizeR': 'no label', 'SLCo_12/31': 'no label', 'SLCo_1/31/': 'no label', 'SLCo_2/29/': 'no label', 'SLCo_3/31/': 'no label', 'SLCo_4/30/': 'no label', 'SLCo_5/31/': 'no label', 'SLCo_6/30/': 'no label', 'SLCo_7/31/': 'no label', 'SLCo_8/31/': 'no label', 'SLCo_9/30/': 'no label', 'SLCo_10/31': 'no label', 'SLCo_11/30': 'no label', 'SLCo_12/_1': 'no label', 'SLCo_1/3_1': 'no label', 'SLCo_2/28/': 'no label', 'SLCo_3/3_1': 'no label', 'SLCo_ZIP_c': 'no label', 'SLCo_Case_': 'no label', 'SLCo_Morta': 'no label', 'SLCo_Vax_c': 'no label', 'Zip.Pop_id': 'no label', 'Zip.Pop_To': 'no label', 'Zip.Pop_Wh': 'no label', 'Zip.Pop_%': 'no label', 'Zip.Pop_Bl': 'no label', 'Zip.Pop__1': 'no label', 'Zip.Pop_As': 'no label', 'Zip.Pop__2': 'no label', 'Zip.Pop_Hi': 'no label', 'Zip.Pop__3': 'no label', });
lyr_Jan21_3.set('fieldLabels', {'OBJECTID': 'no label', 'ZIP5': 'no label', 'COUNTYNBR': 'no label', 'NAME': 'no label', 'SYMBOL': 'no label', 'SHAPE_Leng': 'no label', 'SHAPE_Area': 'no label', 'Case Rate': 'no label', 'Population': 'no label', 'White': 'no label', 'Black': 'no label', 'Asian': 'no label', 'Hispanic': 'no label', 'Dec. 19': 'no label', 'Jan.20': 'no label', 'Feb.20': 'no label', 'Mar.20': 'no label', 'Dec.20': 'no label', 'Jan.21': 'no label', 'Feb.21': 'no label', 'Mar.21': 'no label', 'SLCo_Regio': 'no label', 'SLCo_SizeR': 'no label', 'SLCo_12/31': 'no label', 'SLCo_1/31/': 'no label', 'SLCo_2/29/': 'no label', 'SLCo_3/31/': 'no label', 'SLCo_4/30/': 'no label', 'SLCo_5/31/': 'no label', 'SLCo_6/30/': 'no label', 'SLCo_7/31/': 'no label', 'SLCo_8/31/': 'no label', 'SLCo_9/30/': 'no label', 'SLCo_10/31': 'no label', 'SLCo_11/30': 'no label', 'SLCo_12/_1': 'no label', 'SLCo_1/3_1': 'no label', 'SLCo_2/28/': 'no label', 'SLCo_3/3_1': 'no label', 'SLCo_ZIP_c': 'no label', 'SLCo_Case_': 'no label', 'SLCo_Morta': 'no label', 'SLCo_Vax_c': 'no label', 'Zip.Pop_id': 'no label', 'Zip.Pop_To': 'no label', 'Zip.Pop_Wh': 'no label', 'Zip.Pop_%': 'no label', 'Zip.Pop_Bl': 'no label', 'Zip.Pop__1': 'no label', 'Zip.Pop_As': 'no label', 'Zip.Pop__2': 'no label', 'Zip.Pop_Hi': 'no label', 'Zip.Pop__3': 'no label', });
lyr_Dec20_4.set('fieldLabels', {'OBJECTID': 'no label', 'ZIP5': 'no label', 'COUNTYNBR': 'no label', 'NAME': 'no label', 'SYMBOL': 'no label', 'SHAPE_Leng': 'no label', 'SHAPE_Area': 'no label', 'Case Rate': 'no label', 'Population': 'no label', 'White': 'no label', 'Black': 'no label', 'Asian': 'no label', 'Hispanic': 'no label', 'Dec. 19': 'no label', 'Jan.20': 'no label', 'Feb.20': 'no label', 'Mar.20': 'no label', 'Dec.20': 'no label', 'Jan.21': 'no label', 'Feb.21': 'no label', 'Mar.21': 'no label', 'SLCo_Regio': 'no label', 'SLCo_SizeR': 'no label', 'SLCo_12/31': 'no label', 'SLCo_1/31/': 'no label', 'SLCo_2/29/': 'no label', 'SLCo_3/31/': 'no label', 'SLCo_4/30/': 'no label', 'SLCo_5/31/': 'no label', 'SLCo_6/30/': 'no label', 'SLCo_7/31/': 'no label', 'SLCo_8/31/': 'no label', 'SLCo_9/30/': 'no label', 'SLCo_10/31': 'no label', 'SLCo_11/30': 'no label', 'SLCo_12/_1': 'no label', 'SLCo_1/3_1': 'no label', 'SLCo_2/28/': 'no label', 'SLCo_3/3_1': 'no label', 'SLCo_ZIP_c': 'no label', 'SLCo_Case_': 'no label', 'SLCo_Morta': 'no label', 'SLCo_Vax_c': 'no label', 'Zip.Pop_id': 'no label', 'Zip.Pop_To': 'no label', 'Zip.Pop_Wh': 'no label', 'Zip.Pop_%': 'no label', 'Zip.Pop_Bl': 'no label', 'Zip.Pop__1': 'no label', 'Zip.Pop_As': 'no label', 'Zip.Pop__2': 'no label', 'Zip.Pop_Hi': 'no label', 'Zip.Pop__3': 'no label', });
lyr_Mar20_5.set('fieldLabels', {'OBJECTID': 'no label', 'ZIP5': 'no label', 'COUNTYNBR': 'no label', 'NAME': 'no label', 'SYMBOL': 'no label', 'SHAPE_Leng': 'no label', 'SHAPE_Area': 'no label', 'Case Rate': 'no label', 'Population': 'no label', 'White': 'no label', 'Black': 'no label', 'Asian': 'no label', 'Hispanic': 'no label', 'Dec. 19': 'no label', 'Jan.20': 'no label', 'Feb.20': 'no label', 'Mar.20': 'no label', 'Dec.20': 'no label', 'Jan.21': 'no label', 'Feb.21': 'no label', 'Mar.21': 'no label', 'SLCo_Regio': 'no label', 'SLCo_SizeR': 'no label', 'SLCo_12/31': 'no label', 'SLCo_1/31/': 'no label', 'SLCo_2/29/': 'no label', 'SLCo_3/31/': 'no label', 'SLCo_4/30/': 'no label', 'SLCo_5/31/': 'no label', 'SLCo_6/30/': 'no label', 'SLCo_7/31/': 'no label', 'SLCo_8/31/': 'no label', 'SLCo_9/30/': 'no label', 'SLCo_10/31': 'no label', 'SLCo_11/30': 'no label', 'SLCo_12/_1': 'no label', 'SLCo_1/3_1': 'no label', 'SLCo_2/28/': 'no label', 'SLCo_3/3_1': 'no label', 'SLCo_ZIP_c': 'no label', 'SLCo_Case_': 'no label', 'SLCo_Morta': 'no label', 'SLCo_Vax_c': 'no label', 'Zip.Pop_id': 'no label', 'Zip.Pop_To': 'no label', 'Zip.Pop_Wh': 'no label', 'Zip.Pop_%': 'no label', 'Zip.Pop_Bl': 'no label', 'Zip.Pop__1': 'no label', 'Zip.Pop_As': 'no label', 'Zip.Pop__2': 'no label', 'Zip.Pop_Hi': 'no label', 'Zip.Pop__3': 'no label', });
lyr_Feb20_6.set('fieldLabels', {'OBJECTID': 'no label', 'ZIP5': 'no label', 'COUNTYNBR': 'no label', 'NAME': 'no label', 'SYMBOL': 'no label', 'SHAPE_Leng': 'no label', 'SHAPE_Area': 'no label', 'Case Rate': 'no label', 'Population': 'no label', 'White': 'no label', 'Black': 'no label', 'Asian': 'no label', 'Hispanic': 'no label', 'Dec. 19': 'no label', 'Jan.20': 'no label', 'Feb.20': 'no label', 'Mar.20': 'no label', 'Dec.20': 'no label', 'Jan.21': 'no label', 'Feb.21': 'no label', 'Mar.21': 'no label', 'SLCo_Regio': 'no label', 'SLCo_SizeR': 'no label', 'SLCo_12/31': 'no label', 'SLCo_1/31/': 'no label', 'SLCo_2/29/': 'no label', 'SLCo_3/31/': 'no label', 'SLCo_4/30/': 'no label', 'SLCo_5/31/': 'no label', 'SLCo_6/30/': 'no label', 'SLCo_7/31/': 'no label', 'SLCo_8/31/': 'no label', 'SLCo_9/30/': 'no label', 'SLCo_10/31': 'no label', 'SLCo_11/30': 'no label', 'SLCo_12/_1': 'no label', 'SLCo_1/3_1': 'no label', 'SLCo_2/28/': 'no label', 'SLCo_3/3_1': 'no label', 'SLCo_ZIP_c': 'no label', 'SLCo_Case_': 'no label', 'SLCo_Morta': 'no label', 'SLCo_Vax_c': 'no label', 'Zip.Pop_id': 'no label', 'Zip.Pop_To': 'no label', 'Zip.Pop_Wh': 'no label', 'Zip.Pop_%': 'no label', 'Zip.Pop_Bl': 'no label', 'Zip.Pop__1': 'no label', 'Zip.Pop_As': 'no label', 'Zip.Pop__2': 'no label', 'Zip.Pop_Hi': 'no label', 'Zip.Pop__3': 'no label', });
lyr_Jan20_7.set('fieldLabels', {'OBJECTID': 'no label', 'ZIP5': 'no label', 'COUNTYNBR': 'no label', 'NAME': 'no label', 'SYMBOL': 'no label', 'SHAPE_Leng': 'no label', 'SHAPE_Area': 'no label', 'Case Rate': 'no label', 'Population': 'no label', 'White': 'no label', 'Black': 'no label', 'Asian': 'no label', 'Hispanic': 'no label', 'Dec. 19': 'no label', 'Jan.20': 'no label', 'Feb.20': 'no label', 'Mar.20': 'no label', 'Dec.20': 'no label', 'Jan.21': 'no label', 'Feb.21': 'no label', 'Mar.21': 'no label', 'SLCo_Regio': 'no label', 'SLCo_SizeR': 'no label', 'SLCo_12/31': 'no label', 'SLCo_1/31/': 'no label', 'SLCo_2/29/': 'no label', 'SLCo_3/31/': 'no label', 'SLCo_4/30/': 'no label', 'SLCo_5/31/': 'no label', 'SLCo_6/30/': 'no label', 'SLCo_7/31/': 'no label', 'SLCo_8/31/': 'no label', 'SLCo_9/30/': 'no label', 'SLCo_10/31': 'no label', 'SLCo_11/30': 'no label', 'SLCo_12/_1': 'no label', 'SLCo_1/3_1': 'no label', 'SLCo_2/28/': 'no label', 'SLCo_3/3_1': 'no label', 'SLCo_ZIP_c': 'no label', 'SLCo_Case_': 'no label', 'SLCo_Morta': 'no label', 'SLCo_Vax_c': 'no label', 'Zip.Pop_id': 'no label', 'Zip.Pop_To': 'no label', 'Zip.Pop_Wh': 'no label', 'Zip.Pop_%': 'no label', 'Zip.Pop_Bl': 'no label', 'Zip.Pop__1': 'no label', 'Zip.Pop_As': 'no label', 'Zip.Pop__2': 'no label', 'Zip.Pop_Hi': 'no label', 'Zip.Pop__3': 'no label', });
lyr_Dec19_8.set('fieldLabels', {'OBJECTID': 'no label', 'ZIP5': 'no label', 'COUNTYNBR': 'no label', 'NAME': 'no label', 'SYMBOL': 'no label', 'SHAPE_Leng': 'no label', 'SHAPE_Area': 'no label', 'Case Rate': 'no label', 'Population': 'no label', 'White': 'no label', 'Black': 'no label', 'Asian': 'no label', 'Hispanic': 'no label', 'Dec. 19': 'no label', 'Jan.20': 'no label', 'Feb.20': 'no label', 'Mar.20': 'no label', 'Dec.20': 'no label', 'Jan.21': 'no label', 'Feb.21': 'no label', 'Mar.21': 'no label', 'SLCo_Regio': 'no label', 'SLCo_SizeR': 'no label', 'SLCo_12/31': 'no label', 'SLCo_1/31/': 'no label', 'SLCo_2/29/': 'no label', 'SLCo_3/31/': 'no label', 'SLCo_4/30/': 'no label', 'SLCo_5/31/': 'no label', 'SLCo_6/30/': 'no label', 'SLCo_7/31/': 'no label', 'SLCo_8/31/': 'no label', 'SLCo_9/30/': 'no label', 'SLCo_10/31': 'no label', 'SLCo_11/30': 'no label', 'SLCo_12/_1': 'no label', 'SLCo_1/3_1': 'no label', 'SLCo_2/28/': 'no label', 'SLCo_3/3_1': 'no label', 'SLCo_ZIP_c': 'no label', 'SLCo_Case_': 'no label', 'SLCo_Morta': 'no label', 'SLCo_Vax_c': 'no label', 'Zip.Pop_id': 'no label', 'Zip.Pop_To': 'no label', 'Zip.Pop_Wh': 'no label', 'Zip.Pop_%': 'no label', 'Zip.Pop_Bl': 'no label', 'Zip.Pop__1': 'no label', 'Zip.Pop_As': 'no label', 'Zip.Pop__2': 'no label', 'Zip.Pop_Hi': 'no label', 'Zip.Pop__3': 'no label', });
lyr_Dec19_8.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});